### ISSUE TITLE
Connecting to Alpha Vantage

### ISSUE THREAD

**Issue by benrawson** [bartchr808/Quantopian_Pairs_Trader#1]
Hi Bart, learning python here and keen to get a variation on your script running on Alpha Vantage API. Do you have a simple fix for that please? Thanks!

**Comment by bartchr808** [comment]
Hi @benrawson ! I haven't used Alpha Vantage before, so I'm not sure how to adapt the model to work with it. If you are able to fix it, feel free to submit a PR!
